### ISSUE TITLE
Integration testing with testcontainers

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#100]
Let's try to create an integration test with testcontainers and a docker-compose setup. I already have the docker-compose part ready. Just need to get started with the testcontainers part.

**Comment by andregasser** [comment]
@bocops Yesterday, I realized that the `getInstanceVersion` call in `MastodonClient` was failing when used against real Mastodon servers. Root cause was a simple JSON parsing issue that did not popup during mock testing.

In orde to avoid more cases like this after release, I would like to setup a basic integration test suite based on testcontainers, covering the most important functionality of the library. Just to get higher confidence, that everything is working that should work.

Hope to get it done within the next couple of days. 

For the 2.0.0 release, I am still confident that we can release it in January though.

**Comment by bocops** [comment]
Quality over speed, any time. I'll find some things to document and refactor in the meantime. ;)
