### ISSUE TITLE
Rename Parameter to Parameters

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#105]
Our class currently called `Parameter` is actually a parameter list, and should be renamed accordingly: [Parameter.kt](https://github.com/andregasser/bigbone/blob/master/bigbone/src/main/kotlin/social/bigbone/Parameter.kt)

This is a small but breaking change. Preferably, it would still go into 2.0.0 - but could otherwise wait for the next major release. I can prepare a PR quickly.

**Comment by andregasser** [comment]
Good point. Let's do this in the 2.0.0 release. Then it's out of our way 👍

**Comment by andregasser** [comment]
Please see my comment in the PR.

**Comment by andregasser** [comment]
Closed with https://github.com/andregasser/bigbone/pull/106
