### ISSUE TITLE
Using undocumented OAuth method?

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#11]
There's a `postUserNameAndPassword()` method that gets an access token by posting user credentials to the `/oauth/token` endpoint directly while using a `"grant_type":"password"` parameter:

https://github.com/andregasser/mastodon4j/blob/c19e7a3b728faa345ea71fbdb1231b3e627be2d6/mastodon4j/src/main/kotlin/com/sys1yagi/mastodon4j/api/method/Apps.kt#L90-L118

This method is used in [example code](https://github.com/andregasser/mastodon4j/blob/c19e7a3b728faa345ea71fbdb1231b3e627be2d6/sample-kotlin/src/main/kotlin/com/sys1yagi/mastodon4j/sample/Authenticator.kt#L74) of this project, from where I got the idea to also use it in my PR #10. 

This parameter seems to be not officially supported by the Mastodon API, which only mentions parameter values `authorization_code` and `client_credentials`: [Mastodon API documentation for /oauth/token](https://docs.joinmastodon.org/methods/oauth/#token)

Apparently, sending username/password works via Mastodon's Doorkeeper configuration [here](https://github.com/mastodon/mastodon/blob/ed07f10ca8d4e65ec58958f300a8bb7c762ccbbd/config/initializers/doorkeeper.rb#L165), which explicitly warns about enabling the `password` grant flow, linking to: https://www.rfc-editor.org/rfc/rfc6819#section-4.4.3

I think we need to deal with this one way or another, although I'm not sure how. We should either
- remove functionality that is not part of the documented API completely, because it might fail at any moment, or at least
- document the above both in code and in places like USAGE.md, and urge users to properly use OAuth instead.

**Comment by andregasser** [comment]
Hey @bocops , thanks for your thoughts on this! I think we should support what's officially provided by the Mastodon API documentation. I also see some risks of stuff suddenly breaking.

**Comment by bocops** [comment]
In that case, I believe we should

- [ ] immediately remove example from USAGE.md and mark the mentioned method as deprecated in Apps.kt and RxApps.kt
- [ ] for the next major release, move that method out of Apps.kt into the sample app and also remove related tests;
- [ ] eventually, refactor the sample app to use proper OAuth flow

I will send a PR that takes care of the first task; for the second task, the 2.0.0 milestone should be added to this issue.

**Comment by andregasser** [comment]
Hey @bocops , thanks for the PR - reviewed and merged. Just one question regarding the second task in your previous comment: I guess you're talking about removing the `postUserNameAndPassword` method from `Apps.kt` and `RxApps.kt`right? If so, sure, makes sense. Yes, we also should refactor the example apps. They are still using the `postUserNameAndPassword` in some locations.

Added milesone 2.0.0 to this issue.

**Comment by bocops** [comment]
Yes, exactly. I believe the method in RxApps.kt is unused in the codebase, so it could simply be removed for 2.0.0. The Apps.kt method could be moved first, then removed later if refactoring the example app is not as urgent
