### ISSUE TITLE
Align scope defaults with Mastodon API

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#116]
`AppMethods.createApp()` currently defaults to all scopes if none are given. The endpoint that is called defaults to only read scope if none is given: [Mastodon documentation](https://docs.joinmastodon.org/methods/apps/#create).

We should default to the same values, and not request more. Breaking change, because our current default value allows more than would be allowed after this change.

Other API methods that send a scope should also be checked.

**Comment by andregasser** [comment]
Let's fix this in the 2.0.0 then.
