### ISSUE TITLE
Allow idempotency key to be attached when posting status

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#118]
[Mastodon API: Post a new status](https://docs.joinmastodon.org/methods/statuses/#create) allows for an "idempotency key" to be added when trying to post a new status, "to prevent duplicate submissions of the same status".

This key would probably need to be an optional parameter to be used by library users calling this method. Seems like a useful enhancement to be added soon.

**Comment by andregasser** [comment]
Yes, let's add it in the 2.1.0 release.

**Comment by bocops** [comment]
Given that this key is currently only used when posting a status, and only to avoid duplicated statuses with the same content, I wonder:

1. Does this need to be an optional parameter, or should it be mandatory whenever posting a status?
2. If mandatory, is there really any benefit to allowing our library users to define that string themselves, or can we just generate a string ourselves (for example by hashing the whole parameters list for the request, which basically **is** the content of the status to be posted)?

I can currently see no harm in doing this, although I might be missing something.

**Comment by bocops** [comment]
Reopening, there has been one request to make this idempotency key at least optional, if not user-defined.

**Comment by bocops** [comment]
(re 2): This is not a problem, because the media IDs are part of the parameter list being hashed, thus leading to different key values for attempted posts with different images. At the same time, attempting a repost using the same media IDs will lead to the same key value.

(re 3): I think this is based on a misconception of what problem this idempotency key value is trying to solve. It is not an abuse prevention mechanic, but something that is supposed to prevent accidental "duplicate submissions of the same status", for example if the connection is unstable and posting of a status is retried, although the original request did go through. As such, posting with an idempotency key value X multiple times, resulting in the status being posted exactly once and the same status being returned each time, is exactly the intended functionality and thus should not raise an exception.

(re 4): Accessing the ID of a status is done after that status has been returned. A 404 error can not happen at that moment, I've asked for clarification on that.

This leaves the valid concern (1), we should allow for an idempotency key value to **not** be added to posting requests if the library user wants to disable this functionality.

**Comment by andregasser** [comment]
Hello @bocops,

Thanks for the analysis. regarding 1) :
What about making this optional, with a signature for `postStatus` like this:

```kotlin
    fun postStatus(
        status: String,
        visibility: Status.Visibility = Status.Visibility.Public,
        inReplyToId: String? = null,
        mediaIds: List<String>? = null,
        sensitive: Boolean = false,
        spoilerText: String? = null,
        language: String? = null,
       addIdempotencyKey: Boolean? = false
    ): MastodonRequest<Status> {
```

**Comment by bocops** [comment]
It would definitely be better, and I think a good enough short-term fix. Long-term, it might be useful to allow library users to provide their own idempotency key value.

An example would be the Content Mover tool trying to post two statuses that were originally posted on different dates, but which have the same text content. Perhaps each of them is part of a different thread, so both of them **need** to be created separately and they can't use the same (auto-generated) key value. Individually, though, each of them should not be accidentally duplicated because of a connection issue, so both of them should use a (different) key value that can only be provided by the library user, because only they know when two statuses are logically different.

I think we should solve that part when we create a Builder for posting statuses. Otherwise, our method signatures would become even more unwieldy. :)

**Comment by andregasser** [comment]
Good point, `true` should be default. I forgot about the "default library user" who uses this lib eventually.
Yes, when we go to the builders, we could even let the user provide an implementation of an idempotency generator algorithm, e.g. something like this:

```kotlin
builder.setIdempotencyKeyAlgorithm(myImpl)
```

with an interface behind.
