### ISSUE TITLE
Intermittent log warning about leaked OkHttp connection

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#123]
While testing this library in an Android sample app, I saw this log warning from OkHttp:

> A connection to [URL of Mastodon instance] was leaked. Did you forget to close a response body?

I've not seen this warning anymore after fixing a bug in my own code that led to a weird mismatch of authentication credentials that I can't currently reproduce, but _assume_ it might have to do with a server response that is considered not successful in `MastodonRequest.execute()` [link](https://github.com/andregasser/bigbone/blob/f71d2e0b78081c55059fc875254f9c46145a4bf7/bigbone/src/main/kotlin/social/bigbone/MastodonRequest.kt#L38).

According to https://github.com/square/okhttp/issues/2311, using `response.body?.string()` should close the connection in the successful case, but our `Response` already has a reference to a body that would need to be closed even in the unsuccessful case.

I don't know exactly how to proceed here without being able to reproduce and test, and it seems as if the worst case is a delayed garbage collection.

**Comment by andregasser** [comment]
Thanks for reporting it. What type of library call did you use when that message appeared? Also, do you remember what Mastodon server version you were connected to? I will setup some integration tests very soon (just to have an eye on it).

**Comment by bocops** [comment]
Server version is `v4.0.2`.

I'm using these methods to authenticate:

```
val publicClient = MastodonClient.Builder(instanceName).build()
publicClient.apps.createApp(...).execute()
publicClient.oauth.getOAuthUrl(...).execute()
publicClient.oauth.getAccessToken(...).execute()
```

Then I create another client with access token to do some simple reading/posting:

```
val authClient = MastodonClient.Builder(instanceName).accessToken(accessTokenString).build()
authClient.timelines.getHomeTimeline().execute()
authClient.statuses.postStatus(...).execute()
```

I believe I may have stored and used outdated strings for either `clientId` and `clientSecret` of the registered app, and/or `authCode` or `accessToken` of the later authentication steps. The most likely culprits in that case would be one of the `oauth` methods, or building the authenticated `MastodonClient` itself.

**Comment by preslavrachev** [comment]
I have just experienced a similar issue while authenticating with `mastodon.social`. I have a web app, which would execute the authentication as part of an HTTP request and then wait for the redirect to a callback endpoint. Occasionally, the endpoint would return an error (for which I cannot extract the original error message). Upon refresh, the same call would authenticate successfully, but then I start getting these same log messages.

**Comment by bocops** [comment]
I've had another look at this. [okhttp3.ResponseBody](https://square.github.io/okhttp/3.x/okhttp/okhttp3/ResponseBody.html) is explicit about the response body needing to be closed via one of a few listed methods. This happens automatically in most of our "success" cases (meaning HTTP 2xx responses) where we actually read data via `response.body?.string()` - but doesn't happen in "unsuccessful" cases (including any HTTP 4xx/5xx) where we don't read anything.

We seem to deal with response bodies in these methods:
- `MastodonRequest.execute()`
- `MastodonClient.performAction()`
- `MastodonClient.Builder.getInstanceVersion()`
- all of StreamingMethods.kt

I'll send a PR that should fix the first three cases. There's already an open issue regarding StreamingMethods, so #87 should contain the fix for the latter case. I assume that this is not the problem we're currently seeing - at least I'm not using any streaming method.

**Comment by illuzor** [comment]
The same after client.statuses.postStatus().execute() call
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1530314/222974476-467369f6-c696-4168-a978-54adf2435fd9.png">

**Comment by lamrongol** [comment]
I've got this error when only writing an approximately same sample code of Streaming:

```
    public static void main(final String[] args) throws BigBoneRequestException, InterruptedException {
        final String instance = args[0];//mastodon.social
        final String accessToken1 = args[1];
        final String accessToken2 = args[2];

        // Instantiate client
        final MastodonClient client1 = new MastodonClient.Builder(instance)
                .accessToken(accessToken1)
                .useStreamingApi()
                .build();

        final Handler handler = new Handler() {
            @Override
            public void onStatus(@NotNull final Status status) {
                //
            }

            @Override
            public void onNotification(@NotNull final Notification notification) {
                // No op
            }

            @Override
            public void onDelete(@NotNull final String id) {
                // No op
            }
        };

        // Start federated timeline streaming and stop after 20 seconds
        try {
            final Shutdownable shutdownable = client1.streaming().federatedPublic(handler);
        } catch (BigBoneRequestException e) {
            e.printStackTrace();
        }
        Thread.sleep(60_000);//Wait 1 minute
        final MastodonClient client2 = new MastodonClient.Builder(instance)
                .accessToken(accessToken2)
                .build();


        Thread.sleep(6 * 60 * 1000);//Wait 6 minutes
        System.out.println("6 minitutes elapsed---------------------------------------------------------------");
        Thread.sleep(120 * 60 * 1000);
    }
```

Error message is following:
```
April 05, 2023 4:27:10 okhttp3.internal.platform.Platform log
WARN: A connection to https://mastodon.social/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
April 05, 2023 4:28:14 khttp3.internal.platform.Platform log
WARN: A connection to https://mastodon.social/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```
I found this error happens by only making clients if even one client opens Streaming. Second error message isn't displayed if `client2` doesn't exist.

**Comment by MastodonContentMover** [comment]
I encountered this today while repeatedly calling _getStatuses_ in _AccountMethods.kt_ (the following line):

```
        Pageable<Status> timeline = authenticatedClient.accounts().getStatuses(accountId, false, false, false, currentRange).execute();
```

It was in a loop and I should've been updating _currentRange_ each time but had forgotten — although that shouldn't have made any difference in terms of this error. I was basically just loading the first 40 statuses over and over again and adding them into an _ArrayList_ each time.

_accountId_ and _currentRange_ were defined as follows:

```
     String accountId = authenticatedClient.accounts().verifyCredentials().execute().getId();
     Range currentRange = new Range(null, null, STATUSES_PER_PAGE);
```

_authenticatedClient_ is a _MastodonClient_ authenticated by calling _getOAuthUrl_ to get a code via the web page OAuth callback (with read and write access) then _getUserAccessTokenWithAuthorizationCodeGrant_ with the code to get the access token.

At the time the error occurred, I was connected to the mas.to Mastodon instance, which is running Mastodon v4.1.2.

Here's a screenshot of my output:

![statuses](https://user-images.githubusercontent.com/129753354/230767448-6cb8e27f-dcdd-4c48-9b47-fc472dedb366.JPG)

As you can see, I'd called the (same) method 21 times and then on the 22nd time it threw the error, but the error didn't actually seem to stop anything from working. The program just kept going.

**Comment by bocops** [comment]
I finally followed the advice to set logging levels and got this stack trace as a result:

```
W/okhttp.OkHttpClient: java.lang.Throwable: response.body().close()
W/okhttp.OkHttpClient:     at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.kt:145)
W/okhttp.OkHttpClient:     at okhttp3.internal.connection.RealCall.callStart(RealCall.kt:170)
W/okhttp.OkHttpClient:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:151)
W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.versionedInstanceRequest(MastodonClient.kt:573)
W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.v1InstanceRequest$bigbone(MastodonClient.kt:550)
W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.getInstanceVersion(MastodonClient.kt:521)
W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.build(MastodonClient.kt:587)
```

As I expected, this points at `MastodonClient.Builder.getInstanceVersion()` ([link](https://github.com/andregasser/bigbone/blob/83a2548ab93254a1809471bd7a1d657cb4c26fb6/bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt#L519-L530)), where we start two requests but potentially only act on one of them: depending on how exactly the filtering/mapping is optimized, if the first request result being streamed is successful, the second one might not be handled at all via `response.body?.string()`, which is necessary for it to be properly closed.

@andregasser I tried coming up with good ways to keep the stream idea but at the same time make sure that all requests are handled completely. I failed. ;) I think we should either handle both requests completely, which makes the streaming process somewhat obsolete - or we should just perform the single v1 request for now and come up with something else only if that one gets deprecated.

**Comment by andregasser** [comment]
@bocops Thanks for looking into this. I was able to reproduce the issue and will run some tests with your code changes. If it's fixed, will happily merge this one. :-)

**Comment by bocops** [comment]
To clarify, the PR might solve the problems while using the streaming API, but does not deal with the separate issue of connection leaking while building the client. So, this will at most fix half the issue. ;)

**Comment by andregasser** [comment]
> I finally followed the advice to set logging levels and got this stack trace as a result:
> 
> ```
> W/okhttp.OkHttpClient: java.lang.Throwable: response.body().close()
> W/okhttp.OkHttpClient:     at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.kt:145)
> W/okhttp.OkHttpClient:     at okhttp3.internal.connection.RealCall.callStart(RealCall.kt:170)
> W/okhttp.OkHttpClient:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:151)
> W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.versionedInstanceRequest(MastodonClient.kt:573)
> W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.v1InstanceRequest$bigbone(MastodonClient.kt:550)
> W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.getInstanceVersion(MastodonClient.kt:521)
> W/okhttp.OkHttpClient:     at social.bigbone.MastodonClient$Builder.build(MastodonClient.kt:587)
> ```
> 
> As I expected, this points at `MastodonClient.Builder.getInstanceVersion()` ([link](https://github.com/andregasser/bigbone/blob/83a2548ab93254a1809471bd7a1d657cb4c26fb6/bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt#L519-L530)), where we start two requests but potentially only act on one of them: depending on how exactly the filtering/mapping is optimized, if the first request result being streamed is successful, the second one might not be handled at all via `response.body?.string()`, which is necessary for it to be properly closed.
> 
> @andregasser I tried coming up with good ways to keep the stream idea but at the same time make sure that all requests are handled completely. I failed. ;) I think we should either handle both requests completely, which makes the streaming process somewhat obsolete - or we should just perform the single v1 request for now and come up with something else only if that one gets deprecated.

We can ditch the streaming code and issue two sequential calls and close each of them (whether they were successful or not). Fine for me.

**Comment by andregasser** [comment]
@bocops Streaming the federated timeline now seems to work fine. I was able to stream the fosstodon.org timeline for more than 15 minutes without a single occurrence of a connection leakage error. So from my perspective, this issue is solved for the moment. Before, I always got an error after about 3-5 minutes. Cool! 😀

**Comment by bocops** [comment]
I've not seen this warning myself with the recent snapshots, even after hours of running my app that connects to an instance every once in a while. This is using other APIs than Streaming, but as per the above comment, Streaming seems to be without issues as well.

I'm closing this issue for the time being, but feel free to reopen/comment if anything pops up again.
