### ISSUE TITLE
Provide full support for status posting endpoint

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#125]
The endpoint for posting statuses is not yet fully supportd by BigBone (e.g. some parameters are not supported, such as "language". The goal of this issue is to make sure the endpoint is fully supported according to the Mastodon API docs: https://docs.joinmastodon.org/methods/statuses/#create

**Comment by bocops** [comment]
I'd like to start working on this. One thing I immediately see is the overloading that is happening on Mastodon's side on the `POST /api/v1/statuses` endpoint. When posting a status, it can:
- optionally contain media IDs (at least I assume this is optional although documentation claims that this parameter is required)
- optionally contain a poll, but this is mutually exclusive with containing media
- optionally be scheduled, in which case the return value changes from `Status` to `ScheduledStatus`.

I think it would be best to **not** overload our single postStatus() method with all of this, but instead offer variants for each sensible combination. This would be at least:
- `postStatus` (immediate, text + optional media)
- `postPoll` (immediate, text + poll data
- `scheduleStatus` (scheduled, text + optional media)
- `schedulePoll` (scheduled, text + poll data)

@andregasser do you see a better way than this?

**Comment by andregasser** [comment]
Hey @bocops, thanks for the initiative. I had a quick look at the API docs [here](https://docs.joinmastodon.org/methods/statuses/#create) and I fully agree with your proposal. Let's do it your way. I like it, especially as it makes the API for the library user easier to use. 

I am still working on the integration testing issue https://github.com/andregasser/bigbone/issues/100. I will very soon post a pull request with an initial approach on integration testing our code towards multiple releases of Mastodon (3.0.0, 4.0.2, etc...). 
When that has happened, we could also immediately add some integration tests for the methods you've mentioned above, to verify, if Mastodon accepts it or not.

Have fun! 

P.S. Going to review your other contributions soon.
