### ISSUE TITLE
Support filters

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#130]
- [ ] implement `Filter`, `FilterKeyword`, `FilterResult`, `FilterStatus` entities: https://docs.joinmastodon.org/entities/Filter/
- [ ] add `filtered` field to Status entity to close #16
- [ ] implement API methods documented here: https://docs.joinmastodon.org/methods/filters/

**Comment by bocops** [comment]
I'd like to work on this next, because I can use it in my own app. According to the [API documentation](https://docs.joinmastodon.org/methods/filters/), there are **v1** API methods that have been deprecated for Mastodon 4.0.0, and **v2** methods that have been added with Mastodon 4.0.0.

Our goal is to support Mastodon's last two major releases, but doing it in this case would mean implementing a lot of stuff that is already deprecated and probably would not be used anywhere (do active instances running Mastodon 3.x.x even still exist?). I think it would be sensible to just implement v2 methods here.

@andregasser what do you think?

**Comment by andregasser** [comment]
I am totally happy if we have a working implementation for 4.x. If there are any requests for making it work for 3.x, we can pick up the discussion again. 😀

**Comment by bocops** [comment]
Having started work on this, I'm sure that I can get some of the methods implemented within the next few days. However, there are some weird choices in the API that I'd rather discuss first - for example, [updating a filter](https://docs.joinmastodon.org/methods/filters/#update) includes having key/value pairs where the key is a mix of (new) keywords and ID values for (existing) keywords, while the value is a mix of booleans, keywords and "destroy" flags.

I'll see what part of this is straightforward and what isn't. :)
