### ISSUE TITLE
Merge AppRegistration and Application entity

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#135]
There's no `AppRegistration` entity present in the Mastodon API documentation. 

`AppMethods.createApp()` in our library returns `AppRegistration` whereas in the Mastodon documentation an object of type `Application` is returned.

Suggestion:
- add `vapid_key`, `client_id`, and `client_secret` to `Application` entity (closes https://github.com/andregasser/bigbone/issues/17)
- Delete `AppRegistration` entity
- Adopt rest of the code to the new situation

Application entity:
https://docs.joinmastodon.org/entities/Application/

create app call:
https://docs.joinmastodon.org/methods/apps/#create

**Comment by bocops** [comment]
I only now see that the class just renamed to `Token` resides in the same auth subdirectory as this `AppRegistration` entity. With both being or being merged to "official" Mastodon entities, should we perhaps get rid of this subdirectory at the same time and move Token from `social.bigbone.api.entity.auth` to `social.bigbone.api.entity`?
