### ISSUE TITLE
Improve JvmOverloads

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#152]
We should review all the methods that use the `@JvmOverloads` annotation and check if we could provide more default arguments to the parameters in the method signature to facilitate API usage from a Java perspective. A good example is the current implementation of the `.postStatus` method in `StatusMethods.kt`. It has three optional parameters but does not provide a default argument for it. The only parameter providing a default argument is `visibility`. 

```kotlin
@JvmOverloads
@Throws(BigBoneRequestException::class)
fun postStatus(
    status: String,
    inReplyToId: String?,
    mediaIds: List<String>?,
    sensitive: Boolean,
    spoilerText: String?,
    visibility: Status.Visibility = Status.Visibility.Public
)
```

This makes the compiler only generate two method overloads for Java developers:

```java
postStatus(String status, String inReplyToId, List<String> mediaIds, boolean sensitive, String spoilerText, Visibility visibility)
postStatus(String status, String inReplyToId, List<String> mediaIds, boolean sensitive, String spoilerText)
```

This is suboptimal, as parameters like `inReplyToId` or `mediaIds` are not mandatory. So we should make sure, Java developers also do not need to provide this value if not needed. The method signature could be optimized like this:

```kotlin
@JvmOverloads
@Throws(BigBoneRequestException::class)
fun postStatus(
    status: String,
    inReplyToId: String? = null,
    mediaIds: List<String>? = null,
    sensitive: Boolean = false,
    spoilerText: String? = null,
    visibility: Status.Visibility = Status.Visibility.Public
)
```

This would result in a lot more method overloads to be generated for Java developers, making the calling site easier and cleaner:

```java
postStatus(String status, String inReplyToId, List<String> mediaIds, boolean sensitive, String spoilerText, Visibility visibility)
postStatus(String status, String inReplyToId, List<String> mediaIds, boolean sensitive, String spoilerText)
postStatus(String status, String inReplyToId, List<String> mediaIds, boolean sensitive)
postStatus(String status, String inReplyToId, boolean sensitive)
postStatus(String status, boolean sensitive)
postStatus(String status)
```

From a Java developers point of view, the code for posting a simple status would change from

```java
MastodonRequest<Status> request = client.statuses()
    .postStatus("Hello World", null, null, false, null).execute();
```

to this

```java
MastodonRequest<Status> request = client.statuses()
    .postStatus("Hello World").execute();
```

JvmOverloads:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-overloads/

Java-Friendly Kotlin:
https://lankydan.dev/java-friendly-kotlin-default-arguments

**Comment by andregasser** [comment]
@bocops This would be quite nice to have in the 2.0.0 release. I know, we're putting more and more stuff into it, but when I saw @grobmeier 's Java example in his recent pull request, I felt committed to improve this. It's quite a massive simplification for the Java devs.

**Comment by grobmeier** [comment]
@andregasser as a non-Kotlin user (hope to change that at some point...) I didn't know this is possible. But seriously, having JvmOverloads would be such a great thing. Especially for a 2.0. Cool stuff

**Comment by bocops** [comment]
Definitely, I was thinking the same thing when adding all those annotations I initially missed to my last PR.

One thing about `@JvmOverloads` that is weird but necessary for it to work at all is that overloaded Java methods are created by removing optional parameters from back to front one by one. That means that, using the same example method, there will never be a method `postStatus(statusText, visibility)`, although that might be quite useful.

For full effect, we would need to arrange parameters with default values from least likely to use that default to most likely to use that default, so that those parameters that will use their default values most often are the first to go. Rearranging parameters is a breaking change, so that would definitely be something for a major release.

Builders (#108) could be an alternative to that - perhaps we can make it a long-term goal to offer builders for any method that has more than X parameters with default values?

**Comment by andregasser** [comment]
Yes, fully agree. Let's go through our *Method classes and see what we can improve in terms of adding default arguments and ordering (as proposed by yourself). I'm also all-in for builders in the longer-term (next major release eventually?).

**Comment by bocops** [comment]
In #154, I checked all methods, adding new default values for parameters where sensible, and sorting parameters along these lines:
- mandatory parameters (example: status text and a timestamp for `schedulePost()`)
- optional parameters, in order from least likely to use the default to most likely to use the default (example: visibility before sensitive/spoiler details before language)
- technical parameters last (example: `Range`)

I left out some methods in OAuth and Accounts, as well as StreamingMethods which still needs a full refactoring.
