### ISSUE TITLE
Add missing fields to Status entity

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#16]
The following fields are currently missing in the Status entity class:

- [x]  poll
- [x] card
- [x] text
- [x] edited_at
- [x] muted
- [x] bookmarked
- [ ] filtered

**Comment by bocops** [comment]
Several of these have been added in #131, except for:
- poll (needs #129)
- filtered (needs #130)

**Comment by andregasser** [comment]
The only attribute missing (according to the list presented at the top of this issue) is the `filtered` field.
