### ISSUE TITLE
It should be written in the README or somewhere that `.execute()` is always required.

### ISSUE THREAD

**Issue by lamrongol** [andregasser/bigbone#199]
By watching the sample code, I noticed `.execute()` is always required when getting a timeline, searching, posting a status, and so on.
I don't think this kind of specification is necessary because I don't think we will be doing the same search or posting many times, but if it is necessary, I think it will cause confusion unless you put in the README or somewhere that we must remember to add `.execute()`.

**Comment by bocops** [comment]
Yes, basically all of our API methods return some variant of `MastodonRequest<T>` - which itself returns `T` after calling `.execute()`. This is something we've inherited from our predecessors, and which at least I haven't questioned so far, although I lately fell into the same trap multiple times.

If we change this, we would probably need to rethink how/when exceptions are thrown as well as our Reactive implementation of the same API, so I'd suggest to keep this in mind for a future `3.0.0` release. Better documentation could of course happen earlier than that.

**Comment by MastodonContentMover** [comment]
Would just like to add that this seemed a little redundant to me, as well, from a Java perspective - I'd presumed it was something that was more natural for the Kotlin coders. One time I forgot to add the execute and spent some time staring at the code wondering what on earth could be wrong before spotting the missing .execute() 😅 

Are there any situations where you'd want to manipulate the object before it was executed? Could there be in the future? (Would there need to be some way to let people do that if the execute() was made implicit in the other methods?)

**Comment by andregasser** [comment]
I agree with you guys that calling `.execute()` on each BigBone requests is unnecessary clutter. I also think there is not much additional value provided by having a `.doOnJson()` method on the `MastodonRequest` object. From my current perspective, without having done indepth analysis, I am fine if we change this for the next major release (which is 3.0.0). 

For the time being, I will add a `Troubleshooting` section to the README.md where we can provide advice to people in case they run into trouble (of whatever kind).
