### ISSUE TITLE
Does streaming.user() method work?

### ISSUE THREAD

**Issue by juananpe** [andregasser/bigbone#208]
I'm trying to test some streaming() methods of BigBone's library. 

The `streaming().localPublic()` method works as expected:

https://github.com/juananpe/BigBoneNotificationsDemo/blob/9dfd6ff4da49b5bd4c6661d6508a27964693b6e0/src/main/java/eus/ehu/notificationsdemo/HelloApplication.java#L43

<img width="1398" alt="image" src="https://github.com/andregasser/bigbone/assets/1078305/cc487c8d-f785-403b-a5f1-51d05ab8c4ab">

But all the tests that I've done with  `client.streaming().user(handler)` have failed (I mean, I'm assuming that if my user @juananpe@mastodon.social gets any notification (a mention, a toot is marked as favorite, a toot is boosted) I should get a notification in the console with this code:

https://github.com/juananpe/BigBoneNotificationsDemo/blob/cb07cf8d8872858d83382aa2f39d23ca618142ba/src/main/java/eus/ehu/notificationsdemo/HelloApplication.java#L43

But as mentioned, I get nothing. Is it working OK or is it that I missunderstood how it should work?

Thanks ind advance.

**Comment by bocops** [comment]
@juananpe the Streaming API is actually one that we haven't touched much in our rewrites so far. That said, the code looks identical to other methods such as the one you mention, so both should work.

Are you sure that the `MastodonClient` you are using to access the Streaming API is properly authenticated with all necessary scopes? According to Mastodon API documentation, accessing the public timelines works with public or app-level authentication, while accessing user data obviously is restricted to a properly authenticated user.

**Comment by juananpe** [comment]
Mmmh...  I know how to reproduce the bug.

First, I double checked that I was using the correct token with the correct top-level scopes for read/write/follow and push:
<img width="600" alt="image" src="https://github.com/andregasser/bigbone/assets/1078305/9113f1d8-7d04-4c02-b6db-72765909310a">

Then , I tried to change BigBone's `StreamFederatedPublicTimeline` Java sample class 
https://github.com/andregasser/bigbone/blob/master/sample-java/src/main/java/social/bigbone/sample/StreamFederatedPublicTimeline.java
to use the `streaming.client()` method instead of the `federatedPublic()` method. And it worked!

So the problem arises when running the `streaming.client()` method inside a thread.
Something like this:

```
 Runnable runnable =
                () -> {
                    Shutdownable shutdownable = null;
                    try {
                        shutdownable = client.streaming().user(handler); // an instance of the Handler class used in the sample code
                    } catch (BigBoneRequestException e) {
                        throw new RuntimeException(e);
                    }
                };

        Thread thread = new Thread(runnable);
        thread.start();
```

I don't know why this code doesn't get notifications, while running the same code directly (without using threads) works fine.  And odder still, the `federatedPublic()` method works fine inside a thread.  ¯\_(ツ)_/¯

**Comment by bocops** [comment]
This is strange, I can't see any other difference other than one needing user authentication while the other doesn't. What about the other four methods currently offered by the Streaming API. Do those fail or work consistently as well - and if so, which does what?

**Comment by juananpe** [comment]
This is very strange because sometimes the code works... and sometimes it does not. I'm starting to think that it's not related to BigBone, but to the streaming API being somewhat unreliable on the server side. So please, feel free to close the issue.

**Comment by bocops** [comment]
@juananpe That unreliability sounds like it might be a timeout issue. I assume you're already using `.useStreamingApi()` when building the MastodonClient, which sets the read timeout to 60 seconds. You could try using something like `.setReadTimeoutSeconds(120L)` instead to increase this value even further and see if it changes anything.

**Comment by bocops** [comment]
Closing this issue as requested.
