### ISSUE TITLE
Switch to nodeinfo for instance version information

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#223]
We're currently retrieving version information from the instance endpoint - which turned out to be problematic in the past, among other things because the best endpoint to retrieve this information from itself changes with the instance version. Relevant code was last touched for #123, there's additional discussion in at least #114 and previously #94.

I just learned about [nodeinfo](https://github.com/jhass/nodeinfo) via the beta documentation of the Pixelfed API [here](https://beta-preview.pixelfed.io/guides/how-to-identify-pixelfed). The equivalent documentation for Mastodon barely exists, but at least the [Routes](https://docs.joinmastodon.org/dev/routes/) page claims that this is officially supported for Mastodon as well. Here is what mastodon.social returns on those endpoints: [/.well-known/nodeinfo](https://mastodon.social/.well-known/nodeinfo), [/nodeinfo/2.0](https://mastodon.social/nodeinfo/2.0)

Switching to using version information retrieved via **nodeinfo** could resolve the issues we've had in the past, most importantly the bootstrapping/versioning one. Further down the line, it might also allow us to better support other platforms that have a Mastodon-compatible API, even if the [version information returned by their instance endpoint](https://beta-preview.pixelfed.io/guides/server-variables) is different from what we'd currently expect from Mastodon servers.

**Comment by andregasser** [comment]
That's actually a good idea. Didn't know about this! It seems, it is there since 2019, added with Mastodon 3.0. 
https://github.com/mastodon/mastodon/pull/12002

So yes, fetching the nodeinfo/2.0 endpoint is fine! Makes our own setup more robust.

**Comment by bocops** [comment]
Great, working on it!
