### ISSUE TITLE
Migrate from gson to KotlinX serialization

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#224]
According to the link below, gson is in maintenance mode. There will be bug fixes but no new feature development. Therefore, Gson should be replaced with something actively maintained. KotlinX serialization was proposed by @PattaFeuFeu , which is a nice fit for this Kotlin library.

https://github.com/google/gson

**Comment by PattaFeuFeu** [comment]
I’d like to pick this one up ✋
