### ISSUE TITLE
Change type of id field in entities to from Long to String if necessary

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#25]
Some entities in the "entity" package specify an "id" attribute of type Long. According to the API docs, ids are not guarenteed to be numeric and should have a data type of String instead. Alle entities should quickly be reviewed against API documentation and data type switched if necessary.

**Comment by bocops** [comment]
The following entities have a Long id where the Mastodon API defines a String id.

- [ ] Account
- [ ] Attachment (MediaAttachment)
- [ ] MastodonList (List)
- [ ] Mention (Status::Mention)
- [ ] Notification
- [ ] Relationship
- [ ] Report
- [ ] Status

**Comment by andregasser** [comment]
Just for reference: This issue was created based on the following issue reported in the mastodon4j project: https://github.com/sys1yagi/mastodon4j/issues/89
