### ISSUE TITLE
Implement Suggestions API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#259]
Mastodon's Suggestion API provides endpoints to retrieve server-generated suggestions on who to follow, based on previous positive interactions. The goal of this task is to implement the following endpoints of this API in BigBone:

- View follow suggestions (v2)
- Remove a suggestion

The Suggestions API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/suggestions/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by G10xy** [comment]
I will develop these as well
