### ISSUE TITLE
Implement Domain Blocks API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#260]
Mastodon's Domain Blocks API allows a user to manage his list of blocked domains. The goal of this task is to implement the following endpoints of this API in BigBone:

- Get domain blocks
- Block a domain
- Unblock a domain

The Domain Blocks API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/domain_blocks/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by PattaFeuFeu** [comment]
I’m going to be working on this. Could you please assign me? @andregasser @bocops
