### ISSUE TITLE
Implement Endorsements API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#261]
Mastodon's Endorsements API allows a user to view the profiles that he is currently featuring on his own profile. The goal of this task is to implement the following endpoints of this API in BigBone:

- View currently featured profiles

The Endorsements API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/endorsements/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by PattaFeuFeu** [comment]
@andregasser Could you please assign me here? I’d like to continue with this one.
