### ISSUE TITLE
Implement Push API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#296]
Mastodon's Push API allows a user to subscribe to and receive push notifications when a server-side notification is received, via the Web Push API. The goal of this task is to implement the following endpoints of this API in BigBone:

- Subscribe to push notifications
- Get current subscription
- Change types of notifications
- Remove current subscription

The Push API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/push/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by G10xy** [comment]
I will try to develop them :+1:
