### ISSUE TITLE
Implement Announcements API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#300]
Mastodon's Announcements API allows a user to view the profiles that he is currently featuring on his own profile. The goal of this task is to implement the following endpoints of this API in BigBone:

- View all announcements
- Dismiss an announcement
- Add a reaction to an announcement
- Remove a reaction from an announcement

The Announcements API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/announcements/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by AnuraagReddy123** [comment]
Hey @andregasser can I try this?

**Comment by PattaFeuFeu** [comment]
@AnuraagReddy123 Sure thing! Looking forward to your contribution. 😊

**Comment by AnuraagReddy123** [comment]
So I ran `gradlew check` and I keep running into this error
```
* What went wrong:
Execution failed for task ':sample-java:compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_341 contains a valid JDK installation.
```
I already have JDK 17 installed but for some reason it is looking in the jre folder for the JDK installation. Is there a way to fix this? I am working on Windows 10

**Comment by PattaFeuFeu** [comment]
@AnuraagReddy123 I don’t have Windows myself so I cannot check but from a quick Google search, this is what popped up: https://stackoverflow.com/a/35623142/1791820

Maybe your `JAVA_HOME` is set in a way that prefers the JRE over the JDK?

**Comment by AnuraagReddy123** [comment]
That was actually one of the first things I tried. After trying multiple things I gave up and did what I should have done in the first place, I just opened the project in WSL. Worked like a charm. I ran `./gradlew check` and everything works! 

Before I start implementing, can you just briefly explain the folder structure and what each folder contains, I am new to Kotlin and gradle in general so some pointers would be really helpful

**Comment by andregasser** [comment]
Hello @AnuraagReddy123 ,

Sure, here we go:

We have five main Gradle modules in the project:
- bigbone: Contains the actual code to call the Mastodon REST API plus tests.
- bigbone-rx: This is the reactive implementation of Bigbone. It is sort of a proxy, as it actually only forwards requests to the main `bigbone` Gradle module.
- buildSrc: This contains Gradle plugin code written in Groovy. You usually don't need to change anything in here, as this is solely used for the build it self. You need to modify it, when you introduce a new dependency for example.
- sample-java: Contains Java sample code that illustrates usage of BigBone. You can run these samples on your local machine if you want.
- sample-kotlin: Same as `sample-java` but written in Kotlin.

There are also some other folders, like:
- config: This contains tooling configuration for code analysis tools like pmd, checkstyle and detekt.
- docker: Contains docker compose configs to spin up a working Mastodon instance that can be used to run integration tests locally on the developer's machine. It basically works but needs some more time to make it work nice.
- gradle: Contains the Gradle version catalog and wrapper configs. This is used for the build only.
- .github: Contains GitHub workflow configurations and dependabot related configs.

I hope this helps.

Cheers,
André

**Comment by AnuraagReddy123** [comment]
Hey I have started implementing the announcement API. Should I make a pull request after I am fully done implementing the feature or can I make a pull request now itself with my partial completed code so that you guys can review it and I can get some doubts clarified?

Also what formatter should I use such that i can pass the `./gradlew check`? I keep getting the error
```
/home/anuraag/bigbone/bigbone/src/main/kotlin/social/bigbone/api/entity/Announcement.kt:1:1 File must end with a newline (\n)
```
This is how the code looks like
![image](https://github.com/andregasser/bigbone/assets/66117695/dc856873-8c2d-46ca-84f8-df5502115acd)

**Comment by PattaFeuFeu** [comment]
> Should I make a pull request after I am fully done implementing the feature or can I make a pull request now itself with my partial completed code so that you guys can review it and I can get some doubts clarified?

Whichever you prefer. As long as it’s clear which version you picked for your PR, we should be fine. 😊 

> Also what formatter should I use such that i can pass the ./gradlew check? I keep getting the error

I’m not using VSCode, but the following looks helpful for your case: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

The line number appears to be off in the error you get. This is about ensuring a blank line at the end of the file so that it doesn’t stop with e.g. `}` but instead ends on an empty line.

**Comment by AnuraagReddy123** [comment]
Hey I have made a PR #309

**Comment by andregasser** [comment]
Also, if the PR is not complete, I suggest that you convert it to a draft PR (there's a button somewhere to do this).
