### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#304]
Add details described [here](https://github.com/andregasser/bigbone/issues/300#issuecomment-1774486116) to the [contribution guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md) to help new developers get up to speed more quickly.

**Comment by andregasser** [comment]
Hello @Yordaniss , sure. Thx!

**Comment by Yordaniss** [comment]
@andregasser  no problem. The job is done, please review my PR and let me know if some changes needs to be provide 🙂
