### ISSUE TITLE
Simplify enum classes

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#305]
As outlined [here](https://github.com/andregasser/bigbone/pull/291#discussion_r1367918549), enum classes can be simplified. Instead of writing code like this:

```kotlin
enum class SourceSuggestion(val value: String) {
    STAFF("staff"),
    PAST_INTERACTIONS("past_interactions"),
    GLOBAL("global")
}
```

we can write code like so:

```kotlin
@Serializable
enum class SourceSuggestion {
    @SerialName("staff")
    STAFF,

    @SerialName("past_interactions")
    PAST_INTERACTIONS,

    @SerialName("global")
    GLOBAL
}
```

Doing so we let the serializer do the translation work for us and we can simplify the constructor.

All the enum classes in the project should be reviewed and simplified if it makes sense.

**Comment by GiovanniDesiderioKP** [comment]
Assign me this, so that I will try to refactor any enum used within any dto model

**Comment by G10xy** [comment]
Assign me this, so that I will try to refactor any enum used within any sto model

**Comment by G10xy** [comment]
Just a question: let's take in consideration the Enum CardType. This enum was made to restrict the possible values for the attribute "type" of the PreviewCard dto model. 
Should I update the "type" attribute as Type  
`  @SerialName("type")
    val type: CardType = CardType.Link,`

or remain it as String?
`    @SerialName("type")
    val type: String = CardType.Link.name.lowercase(),`

**Comment by andregasser** [comment]
Hello @G10xy I'd switch this to type `CardType`.
