### ISSUE TITLE
Build a GitHub Actions bases workflow to release the library (snapshots and releases)

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#314]
As discussed on Slack, it would be a good idea to migrate the existing procedure for releasing the library to a GitHub Actions based workflow, as it removes a bottleneck of having only a single person which is capable of releasing a new version.

The current procedure is roughly documented here: https://github.com/andregasser/bigbone/wiki/Publish-a-New-Snapshot-to-MavenCentral

The private key should be stored on GitHub as a secret.

**Comment by PattaFeuFeu** [comment]
I’ll create a PR for this one soon ✋
