### ISSUE TITLE
Implement Admin IP Blocks API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#320]
Mastodon's Admin IP Blocks API allows an admin to prevent certain IP address ranges from signing up. The goal of this task is to implement the following endpoints of this API in BigBone:

- List all IP blocks
- Get a single IP block
- Block an IP address range from signing up
- Update a domain block
- Delete an IP block

The Admin IP Blocks API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/admin/ip_blocks/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by PattaFeuFeu** [comment]
It probably makes sense to wait for #333 to be reviewed and merged. I have made some decisions there that will likely influence the style of this issue here as well, such as:
* `admin` package

**Comment by G10xy** [comment]
Since I see that #333 has been merged, I think it is possible to proceed now with admin-related methods. Assign me this issue, I would like to try to implement it

**Comment by PattaFeuFeu** [comment]
@G10xy Sure thing! Thanks for coming back 😊
