### ISSUE TITLE
Implement Admin Domain Allows API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#328]
Mastodon's Admin Domain Allows API allows an admin to configure which domains are allowed to federate. The goal of this task is to implement the following endpoints of this API in BigBone:

- List all allowed domains
- Get a single allowed domain
- Allow a domain to federate
- Delete an allowed domain

The Admin Domain Allows API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/admin/domain_allows/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by PattaFeuFeu** [comment]
It probably makes sense to wait for #333 to be reviewed and merged. I have made some decisions there that will likely influence the style of this issue here as well, such as:
* `admin` package

**Comment by G10xy** [comment]
Assign me this issue, please
