### ISSUE TITLE
Implement Admin Email Domain Blocks API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#329]
Mastodon's Admin Email Domain Blocks API allows an admin to disallow certain email domains from signing up. The goal of this task is to implement the following endpoints of this API in BigBone:

- List all blocked email domains
- Get a single blocked email domain
- Block an email domain from signups
- Delete an email domain block

The Admin Email Domain Blocks API as it is documented by Mastodon can be found here:
https://docs.joinmastodon.org/methods/admin/email_domain_blocks/

Tip: A lot of other endpoints similar to this have already been implemented. In order to get an idea how to implement this, I suggest that you study the code upfront. Start with one of the `*Methods.kt` files.

Please consult the following documents to make sure your contribution meets our projects criteria:

- [Code of Conduct](https://github.com/andregasser/bigbone/blob/master/CODE_OF_CONDUCT.md)
- [Code Contribution Guidelines](https://github.com/andregasser/bigbone/blob/master/CONTRIBUTING.md)

**Comment by PattaFeuFeu** [comment]
It probably makes sense to wait for #333 to be reviewed and merged. I have made some decisions there that will likely influence the style of this issue here as well, such as:
* `admin` package
* `sealed class` approach for required parameters
* `Key` enum class with `apiName` override
