### ISSUE TITLE
Add library to public list of Mastodon client libraries

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#33]
The site is here: https://docs.joinmastodon.org/client/libraries/#java
We can probably just create a pull request on their repo (did not check in detail yet).
We'll do this after our library 2.0.0 release is either pushed to JitPack or MavenCentral (to be discussed).

**Comment by grobmeier** [comment]
Proposed a PR here:
https://github.com/mastodon/documentation/pull/1122

**Comment by andregasser** [comment]
Hello Christian, we're currently renaming our lib (and the repo) to "bigbone". This should happen within the next few days. Maybe the PR on Mastodon should be revoked or another one created later after the change. Thanks for your help! 👍🏻

**Comment by grobmeier** [comment]
Makes sense, closed the PR for now :)

**Comment by andregasser** [comment]
I would say, we send a PR to Mastodon when we have a first release ready (this would be the 2.0.0 release), so people can start working with a properly released version instead of some dev snapshots. I'd like to publish the library on Maven Central. We will only implement minimal required changes and then push it out so people can start using it.

**Comment by grobmeier** [comment]
Sounds good - release early, release often. And with the current momentum going on. Also Maven central is good idea.

**Comment by andregasser** [comment]
@grobmeier Thanks for your feedback. Happy to hear that we're on the right track. Will gladly come back to you, as soon as we have 2.0.0 ready (in order to hand in the Maston doc pull request once more). Happy holidays till then!  😀

**Comment by andregasser** [comment]
Hello @grobmeier . We have now a 2.0.0-SNAPSHOT on Maven Central ready for testing. Would you mind handing in your pull request with the Mastodon people once more?

**Library Name:**
Bigbone

**Project URL:**
https://github.com/andregasser/bigbone

Thank you very much!

Best regards,
André

**Comment by andregasser** [comment]
Opened a new pull request: https://github.com/mastodon/documentation/pull/1143

**Comment by grobmeier** [comment]
One day out of office, and all work is done already - good for me :) Thanks for the heads up @andregasser but I didn't see this until now

**Comment by andregasser** [comment]
PR closed as it is not yet clear, what the name of the library will be.

**Comment by andregasser** [comment]
We're listed now. Closing this issue.
