### ISSUE TITLE
Type parameter is not properly added to searchContent() method

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#343]
In `SearchMethods.buildParameters()`, `type.name` is added as parameter value. This needs to be lowercase, or we need to return to explicitly giving values in the respective enums.

Changing this fixes #342 for the individual-type case, but not for the generic case. 

https://github.com/andregasser/bigbone/blob/12d6648c6b2da33b433ad24c5f5701657cddc9c4/bigbone/src/main/kotlin/social/bigbone/api/method/SearchMethods.kt#L90C37-L90C37

**Comment by PattaFeuFeu** [comment]
That’s what I went with `apiName` for: https://github.com/andregasser/bigbone/pull/333/files#diff-280566822ab91ce8d3fb06b56002ba761d602539a5587f87b1ce86775fe6ee1fR146
