### ISSUE TITLE
Maven Snapshot

### ISSUE THREAD

**Issue by vvvlll93** [andregasser/bigbone#351]
Hi,

Quick question : when will the next Maven release will be available? Currently, only the last snapshot from 5 November is available. 

Have a lovely day, and thanks for your work.

**Comment by andregasser** [comment]
Hello @vvvlll93 ,

Thanks for asking. I can prepare a new snapshot this week. I'll let you know once it is available.

Best regards,
André

**Comment by vvvlll93** [comment]
Hi @andregasser,

That would be really great! 

Thanks a lot.
V

**Comment by andregasser** [comment]
Hello @vvvlll93,

The new snapshot dated 2023-11-25 has just been published. Check out the release notes here: https://github.com/andregasser/bigbone/releases/tag/v2.0.0-20231125.173242

Best regards,
André

**Comment by vvvlll93** [comment]
Hi @andregasser,

Wonderful! We will check that.

Thanks a lot.

V

**Comment by PattaFeuFeu** [comment]
@vvvlll93 You seem to be using BigBone a bit more. For prioritisation, could you please tell us which API endpoints or which functionality you’re currently missing in the library?

**Comment by vvvlll93** [comment]
Hi @PattaFeuFeu,

We don't have any specific use case that necessitates special functionality. But I can tell you what we want to do, and maybe you'll see what functionality might be missing.

It is pretty straightforward : we want to query a set of server, to get the most data based on one/more keyword, in a minimum of time. That means federated query across multiple servers, and (but I don't know if it is possible) using multiple keywords or conditions, such as language. The query can be based on the statuses directly (i.e. the statuses contain the keyword), or the hashtag (i.e. the statuses contain the hashtag).

If you want i can go a bit deeper to see what might be missing and relevant for us, if it can help you.

Thanks,
V
