### ISSUE TITLE
Remove calls to deprecated instance endpoint

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#424]
We are currently offering `InstanceMethods.getInstanceV1()`, which will get instance information using a deprecated V1 endpoint. Accessing the V2 endpoint is implemented in `InstanceMethods.getInstance()` already.

The V2 endpoint exists since Mastodon server 4.0.0, and all server versions <4.1 are considered to be EOL / unsupported according to https://github.com/mastodon/mastodon/security/policy

- [x] remove `getInstanceV1()` function
- [x] remove `InstanceV1` entity
- [ ] simplify instance version detection in MastodonClient - probably the whole function cascade between `getInstanceVersionViaApi()` and `versionedInstanceRequest()` can be removed

**Comment by bocops** [comment]
> Do you know if we can rely on `getInstanceVersionViaServerInfo()` for all 4.0.0+ server versions or should we still keep the API call?

I assume that we can safely remove the API call. The existence of the Nodeinfo 2.0 endpoint is mentioned in Mastodon's ["Routes" documentation](https://docs.joinmastodon.org/dev/routes/#nodeinfo), even [predating any 4.0 updates to the docs](https://github.com/mastodon/documentation/commits/main/content/en/dev/routes.md).

**Comment by PattaFeuFeu** [comment]
@bocops Ah, nice, that makes it a bit easier to reduce code yet again. Thanks! Will remove it in #452 then.
