### ISSUE TITLE
Build URLs using HttpUrl instead of string concatenation

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#48]
URLs are currently built by simple string concatenation. Building them instead via `okhttp3.HttpUrl` will make the code involved more readable, and might also prevent some bugs down the line.

**Comment by andregasser** [comment]
Good point. Let's add this to the 2.0.0 milestone as well. 

Here a link for reference: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/
