### ISSUE TITLE
Use actual Mastodon examples in tests

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#55]
The Mastodon API documentation defines examples for many of their entities, e.g. the [example for Status entity](https://docs.joinmastodon.org/entities/Status/#example). We might want to use these examples in our tests, to make sure we're testing against up-to-date examples.

**Comment by andregasser** [comment]
Yes, that makes sense. I even thought about integration testing the whole thing, but that might be too much for now.... Let's update the tests we have with the samples from the Mastodon website. That's already a big improvement 😀

**Comment by bocops** [comment]
I have now worked through the JSON files in `/bigbone/src/test/assets`, in each case identified the tests that use them, identified the API method(s) that is/are being tested, copied the example JSON from Mastodon documentation and updated tests as necessary.

There were two problems for which I opened separate issues, but everything else works fine.

I'm now having seconds thoughts if we should really use those exact examples. Most of them seem to be actual results from mastodon.social, sometimes including user IDs, account names, and at least dates of posting if not the post's content itself. Other examples are barely usable because they are incomplete - and even where the example data is extensive, our current tests only use a fraction of it.

Between these extremes, I'm hesitant to commit something that isn't extremely useful at the moment but puts random user data in our commit history. Perhaps we should rather make sure that we get a complete server reply for every entity/method we're updating, anonymize that data and enhance our testing while we're working on individual functionality?

**Comment by andregasser** [comment]
Agree. It's better to capture real and complete server response from Mastodon servers and anonymize them. Eventually, it is also worth capturing the server version that generated the reply (e.g. 4.0.0). We could build a test data structure like `/bigbone/src/test/assets/4.0.0/`etc... Fine for me if we update the test data as we go along updating the endpoints. 

Do you still see some use for the data you have prepared as part pf this issue? Or do you throw it away?



 Mastodon has real user data in their API example responses, so we should anonymize it. It's also fine for me to go through one endpoint by another and improve the test data as we go along.

**Comment by bocops** [comment]
> Do you still see some use for the data you have prepared as part pf this issue? Or do you throw it away?

I'm not sure how useful a patch with that data would be, if it doesn't lead to any bugs popping up right now, and will be changed down the line anyway. One potential use might be while developing the endpoint updates - but even there it might be better to look at relevant tests and update them along with the endpoints themselves.

I can quickly go through and anonymize what problematic content I find, then put it in a branch of my fork to see if it is even useful.

**Comment by andregasser** [comment]
👍🏻

**Comment by bocops** [comment]
As discussed in #67, while some of the example data from Mastodon's documentation might be helpful, in the end it might be best to capture actual live data, anonymize it and use that as our test data going forward. Other example data in the documentation is incomplete and not useful for us.

@andregasser: I updated the title of this issue - but I am unsure whether we should even keep it open? In any case, it is probably best to bump this from the 2.0.0 milestone to a later release, unless we definitely want to update all our test data before that point.

**Comment by andregasser** [comment]
Ok, let's close this for now. I would say, we optimize method placement as discussed in https://github.com/andregasser/bigbone/issues/94 and then aim for releasing the 2.0.0 version soon. Works for me.

**Comment by bocops** [comment]
Yes, something like that would be pretty useful. :)
