### ISSUE TITLE
MastodonLists.getLists() doesn't have range parameter

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#74]
In [MastodonLists.getLists](https://github.com/andregasser/bigbone/blob/e2c2b5e79708139a56c97af1e07c77502acc1da0/bigbone/src/main/kotlin/social/bigbone/api/method/MastodonLists.kt#L14), we're returning a Pageable without using a range parameter - which every other function returning a Pageable has as one of its parameters, e.g. the function directly below.

I couldn't immediately figure out if this is OK or a bug, so I'm listing it here.

**Comment by andregasser** [comment]
Good catch! The docs do not mention query parameters which are part of our `Range` class, like `max_id`, `since_id`, or `limit`. But in their API controller I can see that they are able to process these parameters: https://github.com/mastodon/mastodon/blob/41fe7576bfe8b864d8e1fe018ab3b02b05e02a05/app/controllers/api/v1/lists/accounts_controller.rb#L38

**Comment by bocops** [comment]
Yes, I agree that the first must be the correct one to look at. I assume the second one is related to actually [viewing accounts in a list](https://docs.joinmastodon.org/methods/lists/#accounts). I can do that as soon as #73 went through.

**Comment by andregasser** [comment]
Awesome! Thanks for having a look 👍👍👍
