### ISSUE TITLE
Create a release roadmap

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#77]
In order to plan releases after 2.0.0, we should have some sort of a release roadmap, which outlines what we are working on next. It does not have to be a huge or so, but just help us to prioritize issues to work on and group them into potential releases. Also, we should make sure, we can group breaking changes together as good as we can.

**Comment by andregasser** [comment]
I have enabled the wiki and created a new wiki page for the roadmap (it's currently empty): https://github.com/andregasser/bigbone/wiki/Release-Roadmap

**Comment by andregasser** [comment]
@bocops I have added some issues for a 2.1.0 release. Any suggestions from your side? I thought about eventually support scheduling statuses and/or following/unfollwing hashtags next. But let's discuss.

**Comment by bocops** [comment]
I have to admit I don't yet have a clear picture of what's missing. As 2.0.0 approaches, I'd like to start using this library in some of my own projects, and will probably have better ideas for enhancements at that point. For the time being, I assume there might be others like me, who would use this library not necessarily to build full clients but to use individual functionality to enhance their or their user's Mastodon experience. It might be useful to find out what that individual functionality mostly is.

For me, scheduling statuses (or really anything that is incomplete/bugged in the "post status" department) immediately sound like a useful idea.

Another idea I already have in the back of my head is a dedicated app to manage followers - something along the lines of unfollowing people that have not posted in X time and similar cleanup. For that, anything that is missing in the Account entity and methods that return them would be useful to work on.

Last but not least, if we don't have a clear preference ourselves at some point, we could perhaps create a poll on Mastodon with 3-5 suggestions and see if there's more public interest for one or the other.

**Comment by andregasser** [comment]
Closing this issue. The roadmap is on the wiki. We can work on it as needed.
