### ISSUE TITLE
Move functions getting timelines to Timelines.kt

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#81]
Functions that return timelines are currently spread across various files:
- [Timelines.kt](https://github.com/andregasser/bigbone/blob/master/bigbone/src/main/kotlin/social/bigbone/api/method/Timelines.kt) contains functionality for the home timeline
- [Public.kt](https://github.com/andregasser/bigbone/blob/master/bigbone/src/main/kotlin/social/bigbone/api/method/Public.kt) contains functionality for public and hashtag timelines
- [MastodonLists.kt](https://github.com/andregasser/bigbone/blob/master/bigbone/src/main/kotlin/social/bigbone/api/method/MastodonLists.kt) contains functionality for list timelines

In the Mastodon documentation, all timelines are listed in [one place](https://docs.joinmastodon.org/methods/timelines/#list), so we should probably move all functions into Timelines.kt as well.

**Comment by andregasser** [comment]
Thought exactly the same this morning! Makes sense 👍

**Comment by bocops** [comment]
Yep, should be a quick fix. Already on it. :)
