### ISSUE TITLE
"Get started" guide is outdated/wrong

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#9]
The "Get started" guide (now in [USAGE.md](https://github.com/andregasser/mastodon4j/blob/master/USAGE.md) after move from README.md) is outdated and/or wrong. Just following it from the top, the third line of code

`val statuses: List<Status> = timelines.getPublic().execute()`

is the first one to fail, because Timelines apparently hasn't had a `getPublic()` method for five years. Fixing it to use `getHome()` instead and dealing with it not returning a `List<Status>` but `Pageable<Status>`, this still fails with a Mastodon4jRequestException claiming that I'm unauthorized to do so.

Further down the guide, I see a section about getting the Home Timeline that includes an access token - but that, too, implies that the return value is a List, which it isn't.

In the past, I tried following another part of the guide to get that access token, stumbled upon the incomplete OAuth part, but eventually managed to get _some_ token back from my Mastodon server, only for all attempts at writing a test status to fail, although I requested ALL scope.

Without yet having a full grasp on either Mastodon's API or the way it was implemented here, I'm basically poking random things with a stick to see what moves and what doesn't. I'd love to see working example code that:

- [x] actually implements the complete process to authorize and receive a proper access token, without leaving out some steps
- [x] uses that token to get at least one status from a server (for example the most recent status of the home timeline) and works with it (for example printing its content)
- [x] uses that token to send a status (for example an unlisted "Hello World" status),
- [x] all while having some actually useful comments for the parts left out for some reason.
- [x] EDIT: three items of the comment below should also be handled before closing this.

**Comment by bocops** [comment]
Quoting from the above PR, the following sections are untouched and need to be rewritten or at least checked:

- [ ] Using OAuth
- [ ] Get raw json
- [ ] Streaming API

**Comment by andregasser** [comment]
I have added new sample code for the "Get raw json" case. See commit 7890a67b0656cdfcbea0289be30c43a8e3efb8f9.

**Comment by andregasser** [comment]
I'll take care of the Streaming API example.

**Comment by andregasser** [comment]
Based on the outcome of the discussion [here](https://github.com/andregasser/bigbone/discussions/64) I'd like to close this issue. Streaming API examples are available in both sample modules, `sample` and `sample-kotlin`. @bocops , please shout if you disagree.
